### ISSUE TITLE
Remove label if value is 0

### ISSUE THREAD

**Issue by marcuskyril** [codesuki/react-d3-components#101]
Hello. i was wondering if there's a way to remove the labels on pie chart segments whose values are 0. Thanks in advance!

![image](https://cloud.githubusercontent.com/assets/13675306/17332735/55a6940e-5902-11e6-910e-7b14af0a3159.png)

**Comment by codesuki** [comment]
Thanks for the proposal! Thanks to @solomein we got that fixed. I will release as soon as I incorporated the other current pullreqs.
