### ISSUE TITLE
Relative containers offsets tooltip

### ISSUE THREAD

**Issue by Gasparen** [codesuki/react-d3-components#11]
When using this library with a relative based css (in my case bootstrap) the tooltip is positioned way off. The image shows a small example
![tooltip](https://cloud.githubusercontent.com/assets/9800489/6747855/5e60558e-cedf-11e4-914b-ac72a2d7d691.png)
**css**:
```css
#test {
	position: relative;
	top: 200px;
}
```
**html**:
```html
<div id="test">
	<div id="barchart"></div>
</div>
```

The hotfix beeing used at the moment is changing top and left calculations in TooltipMixin from 
`e.pageY + ...` to `e.nativeEvent.layerY + ...` (and respectivly for x).

I'm unsure whether this is a proper solution to the problem or, as stated, just a hotfix for our case.

**Comment by codesuki** [comment]
Thanks for the report and the example, I will check it!

**Comment by felixhao28** [comment]
+1 on this

**Comment by codesuki** [comment]
Should be fixed in the 0.4.4 release.
I changed the tooltip position to fixed instead of absolute, that should be the correct way. Tested in Firefox, Chrome and Safari.
Maybe you guys can check if it works for you now and report back then I will close this issue :)

**Comment by Gasparen** [comment]
I've tried it out and it works like a charm! :+1:

**Comment by codesuki** [comment]
Thanks for the feedback :)
