### ISSUE TITLE
Bars going out of left Y axis in Grouped Bar chart with Brush when it is extended. Clip path not working.

### ISSUE THREAD

**Issue by kalyanixraut** [codesuki/react-d3-components#116]
I am trying to design a grouped bar chart with a course range selector(or brush feature)across the bottom. Brush is working fine but the bars move to left , crossing the left y-axis when it is extended. How can I avoid it. Same is the case if I use scatter plot.

I tried following the clip path code which is there and working for line chart in group bar and scatter charts, but see no fix.
Please help
KR

**Comment by codesuki** [comment]
Thanks for the report! I will have a look

**Comment by codesuki** [comment]
Hey sorry for the late reply!
Could you show me a code sample so that I can reproduce the problem?
I didn't have time to create one yet. 
But I have an idea what could be the problem.
Again sorry for the late reply.
