### ISSUE TITLE
Change render order of Axes in BarChart

### ISSUE THREAD

**Issue by peterssonjonas** [codesuki/react-d3-components#125]
By rendering the axes first, tick lines will not cover the bars.

I see that some of the graphs (e.g ScatterPlot, LineChart) renders the Axes first and then the actual Dataset, but for the BarChart this is not the case.

I don't know if the current approach is on purpose, but I would like to add tick lines that do not cover the bars.

Currently:
<img width="508" alt="screen shot 2017-02-11 at 11 56 03" src="https://cloud.githubusercontent.com/assets/3624774/22853238/2dddcc9e-f051-11e6-9e22-124c39f75690.png">

What I want:
<img width="509" alt="screen shot 2017-02-11 at 11 57 31" src="https://cloud.githubusercontent.com/assets/3624774/22853241/51219028-f051-11e6-99fb-df68c3ee73c3.png">

**Comment by codesuki** [comment]
Oh wow! I never used that so it never came up. 
Of course the one you proposed looks correct and this is a bug/oversight. 
Would you consider sending a pullreq for that? The earliest I can change it is beginning of next week.

**Comment by codesuki** [comment]
Released in 0.6.6
Thanks again!
