### ISSUE TITLE
Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

### ISSUE THREAD

**Issue by RupaliPatwa** [codesuki/react-d3-components#127]
Hi Follwing is my main file.
I am getting error on browser as  Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.

import React from 'react';
import ReactDOM from 'react-dom';
import BarChart from 'react-d3-components';
var data = [{
    label: 'somethingA',
    values: [{x: 'SomethingA', y: 10}, {x: 'SomethingB', y: 4}, {x: 'SomethingC', y: 3}]
}];

ReactDOM.render(
    <BarChart
        data={data}
        width={400}
        height={400}
        margin={{top: 10, bottom: 50, left: 50, right: 10}}/>,
    document.getElementById('chart-container')
);

**Comment by solomein** [comment]
https://github.com/codesuki/react-d3-components/issues/108#issuecomment-244744035

Also, You did not pass the component to the method `render`
