### ISSUE TITLE
How to override value of tickRotation in barChart

### ISSUE THREAD

**Issue by RupaliPatwa** [codesuki/react-d3-components#130]
Hi,
I want to set value of tickRotation. how do I do that

**Comment by solomein** [comment]
You can set the `tickDirection` parameter to `horizontal `, `vertical ` or  `diagonal`. 
Custom values for `tickDirection` are not currently supported.

**Comment by RupaliPatwa** [comment]
ok. thanks.

**Comment by codesuki** [comment]
@solomein thanks a lot for keeping watch! It's super helpful!
