### ISSUE TITLE
pie charts  label  overlapping and label hidden 

### ISSUE THREAD

**Issue by viveknaragude** [codesuki/react-d3-components#131]
![1](https://cloud.githubusercontent.com/assets/25178257/24703333/72fd63d6-1a20-11e7-8ddf-bbdc753682c4.jpg)
![2](https://cloud.githubusercontent.com/assets/25178257/24703334/7303de82-1a20-11e7-8f20-c83fa59376c1.jpg)
 the issues regarding pie charts  label overlapping and label hidden 
help me if it is not issue and how i can fix it

**Comment by codesuki** [comment]
Interesting problem! I will try to reproduce it and find a fix. Probably have to change the labeling code.

**Comment by viveknaragude** [comment]
Hi codesuki
 you can change the labeling code.

**Comment by codesuki** [comment]
Sorry, not yet :( I am totally swamped by work.

**Comment by codesuki** [comment]
Could you solve the problem by making the pie chart bigger?
The only solutions that come to mind are hiding overlapping labels or making the chart bigger.

**Comment by viveknaragude** [comment]
just told me can i  do this change  in which file

**Comment by viveknaragude** [comment]
making the chart bigger is not good solution

**Comment by codesuki** [comment]
You could fork and play around with `src/PieChart.jsx` to see if you get some better results.

**Comment by viveknaragude** [comment]
ok Thank You..

**Comment by MDB-20** [comment]
@viveknaragude @codesuki  is there a fix for this ?

**Comment by codesuki** [comment]
Maybe here:
https://github.com/thomasdashney/react-d3-components/commit/c1486eb4b54e2554ef773297583dd02c0f9c5c68

@thomasdashney any chance for a pull request?

**Comment by codesuki** [comment]
I pushed the fix. Version 0.6.7.

**Comment by thomasdashney** [comment]
@codesuki :+1: I don't think it's a _great_ solution, but I do think it's better than having no safeguard

**Comment by codesuki** [comment]
@thomasdashney good job! I hope it's okay I integrated your idea there.

**Comment by MDB-20** [comment]
is there a JsFiddle @codesuki  @thomasdashney available ?

**Comment by codesuki** [comment]
That would be a good thing to have. I personally always play around in the example file.

**Comment by codesuki** [comment]
https://jsfiddle.net/3a7s0r1q/1/

**Comment by MDB-20** [comment]
thanks for the fiddle :+1:

**Comment by codesuki** [comment]
It's still using the old version. Will update it in a second.

**Comment by viveknaragude** [comment]
@MDB-20  please update your version its fix (thomasdashney/react-d3-components@c1486eb)

**Comment by codesuki** [comment]
@viveknaragude it's fixed now in 0.6.7

**Comment by carly-rw** [comment]
Can we look into this again? Related to https://github.com/codesuki/react-d3-components/issues/172, this doesn't seem like the optimal behavior in pie charts in which visually there is clearly enough space for multiple labels to appear close to each other.
