### ISSUE TITLE
Is it possible to get area between two lines filled?

### ISSUE THREAD

**Issue by apefisk** [codesuki/react-d3-components#134]
Hi!

I have this linechart with three lines with.
I am wondering if there is any way to get the area between two lines colored/filled?
In this case I would want the "min" and "max" area to be filled.

![image](https://user-images.githubusercontent.com/8640340/27907194-f593fad0-6246-11e7-93cc-f761dce107fe.png)

**Comment by codesuki** [comment]
While it's definitely possible to do in general... the library, sadly :(, only supports one type [line,area,...] per chart. I think that needs changing.

**Comment by apefisk** [comment]
Thank you for answering!
