### ISSUE TITLE
Custom colorScale for LineChart

### ISSUE THREAD

**Issue by felixhao28** [codesuki/react-d3-components#14]
**Edit: Later I found out that it was my css file setting the stroke style. Apparently style has a higher priority than `stroke` attribute.**

Hi codesuki, you implemented the stroke color as an attribute rather than a style:

![image](https://cloud.githubusercontent.com/assets/2417391/6798746/2051685e-d24b-11e4-8720-72e26a3d93f9.png)

However according to [SVG color attributes](http://webdesign.about.com/od/svg/a/svg-color.htm), you can only use named color as an attribute this way. Would you add support for custom valued color such rgb and hex color?

**Comment by felixhao28** [comment]
It can be fixed very easily:

![image](https://cloud.githubusercontent.com/assets/2417391/6798837/d555ba5c-d24b-11e4-8b45-9d78c1370825.png)

**Comment by felixhao28** [comment]
I also need support for `strokeDasharray` attribute.

**Comment by codesuki** [comment]
Yeah I will change that! It's probably a good idea to move some stuff into the style attribute. Thanks for the suggestion.

**Comment by codesuki** [comment]
It will take some days though. If you need it urgently maybe you send a pullreq, if you already know how to implement it.

**Comment by felixhao28** [comment]
My hotfix for custom stroke color will raise a warning in browser. Not sure how to suppress that. And there are many other places where you use `stroke` as an attribute. I suppose we (you) need to make the same changes to them as well.

I added `stroke-dasharray` support for LineChart.

![image](https://cloud.githubusercontent.com/assets/2417391/6818498/c57519b6-d2eb-11e4-8a60-57d676523832.png)

But this is only a specific case of two more general issues:

1. Adding support for `stroke-dasharray` attribute for other components as well.
1. Letting attributes accept functions (data -> attribute_value mappings) as well.

And neither of them seems to be a trivial task.

**Comment by codesuki** [comment]
The graph looks cool :)
Do you mind if, in the future, I include it in the Readme?

But back to topic...
What warning are you getting? 

Anyway I agree with both your points and I will think about how to implement them as soon as I can :)
Would be good to have support for all the SVG attributes here: http://facebook.github.io/react/docs/tags-and-attributes.html

**Comment by felixhao28** [comment]
I certainly don't mind about the graph but my company probably does :(

The warning is something like "`stroke` is a MUST-HAVE attribute you stupid-ass". It is generated by react.js.

**Comment by codesuki** [comment]
Ok don't worry, will not use :)
The missing key warnings should be fixed since today 0.4.4. 
I will try around with the stroke attribute. An warning is annoying but since we will set it via style maybe we can ignore it.

**Comment by codesuki** [comment]
@felixhao28 I tested the stroke prop with rgb(0,0,255) and #0000FF and both worked flawlessly in Chrome, Firefox and Safari. 
Did it actually not work for you in some case or you just refer to the webpage in your first post?

I will add the stroke-dasharray prop today :)

**Comment by felixhao28** [comment]
Oh I just checked and found my css has been setting the stroke in style. No wonder it does not work!

**Comment by codesuki** [comment]
Hehe ok, thanks for checking.

**Comment by felixhao28** [comment]
Thanks for so actively updating this library.

**Comment by codesuki** [comment]
No problem! I would like to do more but work is in the way ;)

**Comment by felixhao28** [comment]
Not yet. What kind of animation are we talking about?

**Comment by codesuki** [comment]
Like barcharts fading in, growing from bottom to top or a real time chart moving from right to left. 
I pushed a test to feature/transition branch, if u want to check out the example.

**Comment by codesuki** [comment]
I added strokeWidth, strokeLinecap and strokeDasharray to LineChart. It's described in the readme under 'customization'. You can supply functions that get passed the label of line.
That is what you needed right? I also uploaded a new version of the example. The one LineChart should show different stroke styles.

**Comment by felixhao28** [comment]
Great, exactly what I was hoping for! A big thank you!

**Comment by felixhao28** [comment]
As for the animation, I may want to use on LineChart. In my case, user has the option to hide/show a new set of lines and to highlight one set (by changing strokedash-array). If animation effects can be applied to the transitions, I would like to try.
