### ISSUE TITLE
A bug in tooltip generation

### ISSUE THREAD

**Issue by felixhao28** [codesuki/react-d3-components#15]
In your code, you have

```js
var indexRight = idx == stack.length ? idx - 1 : idx;
var valueRight = x(values(stack)[indexRight]);
```

but `stack` cannot be guaranteed to be an array and you should use `values` to find the array. Like this:

```js
var indexRight = idx == values(stack).length ? idx - 1 : idx;
var valueRight = x(values(stack)[indexRight]);
```

Otherwise, when user moves mouse outside the xdomain to the right, it will generate an error due to index out of bound.

**Comment by codesuki** [comment]
Oh yeah, nice catch! Stack isn't even supposed to be an array so I don't know what I was thinking there!

**Comment by codesuki** [comment]
Wasn't thinking clear when I changed from the old tooltip code to the new one :) 
Fixed now and will push soon.
