### ISSUE TITLE
Tooltip disappear when cursor moves directly onto the tooltip symbol

### ISSUE THREAD

**Issue by felixhao28** [codesuki/react-d3-components#17]
This is because when cursor moves onto the tooltip symbol, it will trigger a `MouseLeave` event on the main chart and then the event gets caught by TooltipMixin.

**Comment by codesuki** [comment]
True :) 
Will fix today

**Comment by codesuki** [comment]
Should be fixed but I will rewrite the tooltip as discussed in the other issue.
