### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by nhill-cpi** [codesuki/react-d3-components#170]
This is a great repo, thank you @codesuki . Are there any efforts to maintain it going forward?

**Comment by codesuki** [comment]
Hey there. I try to merge PRs if they meet some level of quality but I don't have time to add new features by myself. I wanted to add a message to the README.md to look for a maintainer because it seems many people are still actively using the library.

**Comment by nhill-cpi** [comment]
@codesuki Thanks for letting me know.
