### ISSUE TITLE
Empty data array causes crash

### ISSUE THREAD

**Issue by felixhao28** [codesuki/react-d3-components#18]
I know it is not correct to use empty data array but I just hope the components can be more robust.

**Comment by codesuki** [comment]
Sure! Totally agree:)

**Comment by felixhao28** [comment]
It will be best if there is an option to display something indicating "no data available" rather than an blank board.

**Comment by codesuki** [comment]
Good idea, I was just thinking about how to signal missing data.

**Comment by codesuki** [comment]
For now fixed the crash by supplying a default dataset to the chart. Might not be the best solution but better than crashing, until I have time to think of something better.

**Comment by felixhao28** [comment]
Currently I changed your code so that when the data is null or undefined, there will be a spinning animation and a text showing "loading data...", and when the data is an empty array, there will be a text showing "no data available" and the x-axis and y-axis will still be drawn if given. I think this can be set as the default behavior unless user specifies the element for it when data is not a valid data array.

**Comment by codesuki** [comment]
Can you send a pullreq or something? I would integrate that :)

**Comment by felixhao28** [comment]
No, I only modified LineChart (since I only use that). Other components may require the same respect before sending a pr.

**Comment by codesuki** [comment]
True, anyhow how did you implement the spinner?

**Comment by felixhao28** [comment]
Very easy, it is done by setting background-image to a spinning gif file using css.

**Comment by codesuki** [comment]
Oh well, lol :)
