### ISSUE TITLE
resize issue***

### ISSUE THREAD

**Issue by wer** [codesuki/react-d3-components#26]
In this file: HeightWidthMixin.jsx
i wonder why passing this.pros and not props?

	_calculateInner(props) {
		let {height, width, margin} = this.props;

this causing resize problems....check about it

**Comment by codesuki** [comment]
Bug! Good catch! Thank you.

**Comment by wer** [comment]
next release?

**Comment by codesuki** [comment]
I think I will push in few mins!

**Comment by wer** [comment]
ok, thank you

**Comment by codesuki** [comment]
Done!
