### ISSUE TITLE
Invariant Violation: addComponentAsRefTo with LineChart

### ISSUE THREAD

**Issue by dmmalam** [codesuki/react-d3-components#29]
Hey any ideas what's going on here. I'm trying to add a simple LineChart.

```                
<LineChart
data={{label:'now', values:[{x:0,y:100}, {x:1, y:200}]}}
width={600}
height={400}
margin={{top: 10, bottom: 50, left: 150, right: 10}}
xAxis={{innerTickSize: 5, label: 'Age'}}
yAxis={{label: 'Funds'}}
/> 



Uncaught Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. This usually means that you're trying to add a ref to a component that doesn't have an owner (that is, was not created inside of another component's render method). Try rendering this component inside of a new top-level component which will hold the ref.

invariant.js:43 
invariantReactOwner.js:71
ReactOwner.addComponentAsRefToReactRef.js:24 
attachRefReactRef.js:40 
ReactRef.attachRefsReactReconciler.js:23 
attachRefsCallbackQueue.js:69 
assign.notifyAllReactReconcileTransaction.js:82 ON_DOM_READY_QUEUEING.closeTransaction.js:208 
Mixin.closeAllTransaction.js:149
Mixin.performReactMount.js:270
batchedMountComponentIntoNodeTransaction.js:135 
Mixin.performReactDefaultBatchingStrategy.js:67 ReactDefaultBatchingStrategy.batchedUpdatesReactUpdates.js:111 
batchedUpdatesReactMount.js:405
ReactMount._renderNewRootComponentReactPerf.js:71
ReactPerf.measure.wrapperReactMount.js:494
ReactMount.renderReactPerf.js:71
ReactPerf.measure.wrapperclient.js:46
(anonymous function)client.js:25
gclient.js:46
(anonymous function)client.js:46
/Users/dmmalam/Code/q/goku/app/client.js../app.jsx_prelude.js:1
s_prelude.js:1
e_prelude.js:1 (anonymous function)
```

**Comment by codesuki** [comment]
Hey there, can you show me your surrounding code? The code were the LineChart is embedded? 
I just tested the code you posted inside a empty components render() method and it draws fine for me.
Which React version are you using?

**Comment by dmmalam** [comment]
Hey, I'm trying to isolate the error.
I'm using react 0.13.2 and react-d3-components 0.4.8.

I'm getting the same error even whilst using the simple barchart example on the project page, with it rendering to the root node (ie without the rest of my app). Could it be related to browserify and server side rendering which I also use?

I also get the following error in concert with the Invariant Violation

` Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) <div data-reactid=".1d8h2
 (server) <div id="home" data-react`

Let me whip up a quick isolated example

**Comment by codesuki** [comment]
Hey thanks for investigating! 
I never did server rendering with this library but if you finish the example I will check too and try to fix as necessary to make it work.

**Comment by dmmalam** [comment]
Hey, I've reproduced the checksum error in this gist https://gist.github.com/dmmalam/1f7fd2903876552ab1c3.  

I can't seem to reproduce the ref error, so something may have caused it. I would ignore that for now.

If you clone the gist, and run `npm start` and open a browser at localhost:8000. If you open the console, you should see the error in the logs.

**Comment by codesuki** [comment]
Thanks I'll check it out!

**Comment by dmmalam** [comment]
Hey, any ideas? Or do you want me to investigate further

**Comment by codesuki** [comment]
Sorry I didn't have time yet to check :(

**Comment by clintharrison** [comment]
Just wanted to mention that I'm also having this error, but I'm not doing any server side rendering, just using webpack to bundle everything together and transform the JSX to regular JS.

**Comment by codesuki** [comment]
I am also using webpack. I will post my config later.

**Comment by codesuki** [comment]
@dmmalam  @clintharrison 
Hey I finally came around to test the Gist that your nicely prepared.
I tried it in Chrome and Firefox and it both worked showing me the graph with no error output.
I just did npm install && npm start.

Maybe I missed something? Do you get to see the Graph but there is an error or it's just showing nothing?

**Comment by dmmalam** [comment]
Hey, the graph works, but React gives a warning like below 
![screen shot 2015-06-25 at 18 08 06](https://cloud.githubusercontent.com/assets/19739/8360530/39754c0c-1b65-11e5-816e-ff7e95358551.png)

This warning is crucial as it means the benefits of pre-rendering on the server are lost, and react will redraw again on the client. It most likely occurring because the draw path isn't pure and the same render function running on the server is giving a different result to the client.

You may get also get this error in the console
```
Server started. Open localhost:8000

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: EMFILE, open '/Users/dmmalam/Code/q/testd3co/node_modules/react/package.json'
```

Which I've currently fixed by doing a `ulimit -n 2048` just before executed `node server.js`
I believe this may be a separate issue, as node is hitting the OS max files open per process limit most likely by browserify parsing the source to D3.

**Comment by codesuki** [comment]
Ok thank for the detailed feedback! I will have another look and try to fix it.
The data-reactid is different too that might not be good.
