### ISSUE TITLE
"lineClip" id conflict

### ISSUE THREAD

**Issue by felixhao28** [codesuki/react-d3-components#32]
I noticed that you have set the "clipPath" style of the <path> element in LineChart to "lineClip". If I put two lineCharts, there is an id conflict between these two, causing the chart to be clipped to wrong size.

**Comment by felixhao28** [comment]
An interesting fact is that this conflict does not seem to cause problems on Firefox. Maybe it is a bug in Chrome?

**Comment by codesuki** [comment]
I will check! Thanks for reporting :)

**Comment by codesuki** [comment]
Hahaha great. Yes that was my fault making all my example graphs the same size. I will merge @slomek s pull request that should fix it. Thank you.
