### ISSUE TITLE
Default scale for date values

### ISSUE THREAD

**Issue by AlexPoint** [codesuki/react-d3-components#37]
Hey,

Me again ;)
I'm neither fluent in ES6 nor d3 so I'm not doing any changes myself for now but maybe in the future when I'm more confident.

When creating the default scale for date values, you only specify one value for the domain instead of a range [min, max]
See https://github.com/codesuki/react-d3-components/blob/master/src/DefaultScalesMixin.jsx line 89.

Any reason for that? Because for my specific case, the graph looks much better with a [min, max] scale and I don't see how the current implementation could be better in other cases:

```javascript
var data= JSON.parse("{\"label\":\"\",\"values\":[{\"x\":\"2015-02-07T23:00:00.000Z\",\"y\":2},{\"x\":\"2015-02-22T23:00:00.000Z\",\"y\":1},{\"x\":\"2015-03-04T23:00:00.000Z\",\"y\":2},{\"x\":\"2015-03-08T23:00:00.000Z\",\"y\":3},{\"x\":\"2015-03-10T23:00:00.000Z\",\"y\":1},{\"x\":\"2015-03-11T23:00:00.000Z\",\"y\":1},{\"x\":\"2015-04-04T22:00:00.000Z\",\"y\":2},{\"x\":\"2015-06-27T22:00:00.000Z\",\"y\":1},{\"x\":\"2015-07-31T22:00:00.000Z\",\"y\":2},{\"x\":\"2015-11-15T23:00:00.000Z\",\"y\":1},{\"x\":\"2015-12-29T23:00:00.000Z\",\"y\":1}]}");
<LineChart data={data} width={840} height={500} margin={{top: 10, bottom: 50, left: 50, right: 10}}, xAxis={{tickFormat: d3.time.format("%y-%m-%d")}} />
```
gives this graph (a zoom on the first date of the next chart):
![default scale](https://cloud.githubusercontent.com/assets/1026807/8438832/a44c8aac-1f68-11e5-8f91-a7d8ef3fffb1.PNG)

Now,
```javascript
var data= JSON.parse("{\"label\":\"\",\"values\":[{\"x\":\"2015-02-07T23:00:00.000Z\",\"y\":2},{\"x\":\"2015-02-22T23:00:00.000Z\",\"y\":1},{\"x\":\"2015-03-04T23:00:00.000Z\",\"y\":2},{\"x\":\"2015-03-08T23:00:00.000Z\",\"y\":3},{\"x\":\"2015-03-10T23:00:00.000Z\",\"y\":1},{\"x\":\"2015-03-11T23:00:00.000Z\",\"y\":1},{\"x\":\"2015-04-04T22:00:00.000Z\",\"y\":2},{\"x\":\"2015-06-27T22:00:00.000Z\",\"y\":1},{\"x\":\"2015-07-31T22:00:00.000Z\",\"y\":2},{\"x\":\"2015-11-15T23:00:00.000Z\",\"y\":1},{\"x\":\"2015-12-29T23:00:00.000Z\",\"y\":1}]}");
var dates = _.map(data.values, function(val){ return val.x; });
var minDate = _.min(dates);
var maxDate = _.max(dates);
var scale = d3.time.scale().domain([minDate, maxDate]).range([0, innerWidth]);
<LineChart data={data} scale={scale} width={840} height={500} margin={{top: 10, bottom: 50, left: 50, right: 10}}, xAxis={{tickFormat: d3.time.format("%y-%m-%d")}} />
```
gives this chart:
![custom scale](https://cloud.githubusercontent.com/assets/1026807/8438885/d8f290a8-1f68-11e5-82c8-eabd6bf667e3.PNG)

Am I missing the general case here?

**Comment by codesuki** [comment]
Sorry for the late response. You are correct. According to the D3 documentation it should be possible if amount of X values matches amount of Y values but that might not work out in all cases, also I just tested it and it didn't work. I will change the code to just set min,max date as in your code and also the example.html which already used a custom time scale. Thanks for reporting!
