### ISSUE TITLE
Declare React as peer dependency instead of direct dependency

### ISSUE THREAD

**Issue by fiducioso-dan** [codesuki/react-d3-components#39]
Since this module is an extension of React, it should declare React in the `peerDependencies` list in `package.json` and remove it from the `dependencies` list: http://stackoverflow.com/questions/30451556/what-is-the-correct-way-of-adding-a-dependency-to-react-in-your-package-json-for. I believe that declaring it in `dependencies` causes a second, possibly incompatible copy of React to be installed.

**Comment by codesuki** [comment]
Good call! I will try that. Thanks for your suggestion :)

**Comment by richkeenan** [comment]
+1. I have to import 'react' (lower case) and 'React' (upper case) currently because of this. Not a massive issue but did cause some confusion for a noob like me!

**Comment by codesuki** [comment]
Should be fixed thanks to the pull request.
