### ISSUE TITLE
PieChart does not preserve order of values

### ISSUE THREAD

**Issue by dennisjac** [codesuki/react-d3-components#4]
I just created a small test of a PieChart and noticed that apparently The values are not rendered in the same order as they are provided. When I provide the values [x,y,z] they are instead rendered as for example [y,x,z].

**Comment by codesuki** [comment]
I will have a look. Thanks for noticing!

**Comment by codesuki** [comment]
D3.js sorts the Pie Chart by default but there is a way to disable that. After I thought about how to implement that API-wise I will make that optional.

**Comment by codesuki** [comment]
I added a optional sort= property to the PieChart. It behaves like d3 pie.sort() https://github.com/mbostock/d3/wiki/Pie-Layout 
Default is to sort by value, and if you set the prop to null no sorting will be done. You can also supply your own sort function. Will update Readme and publish update later today.
