### ISSUE TITLE
BarChart: uncaught TypeError: cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by faria** [codesuki/react-d3-components#41]
I'm using version 0.4.8 along with react v0.13.3 to create a BarChart.  I use gulp/browserify/reactify to compile, and that step does not give me any errors.  But, when I try to see the output in the browser, I get the error message:
uncaught TypeError: cannot read property 'x' of undefined from:
getDefaultProps() in StackAccessorMixin

My code looks like this:
var React = require('react');
var d3 = require('d3');
var ReactD3 = require('react-d3-components');

var BarChart = ReactD3.BarChart;

var WeightlogBarChart = React.createClass({
    propTypes: {
        entries: React.PropTypes.array.isRequired,
        user: React.PropTypes.object.isRequired,
        width: React.PropTypes.number.isRequired,
        height: React.PropTypes.number.isRequired
    },
    render: function() {
        var values = this.props.entries.map(function(d) {
            return {x: d.logdate, y:d.weight_lbs};
        });
        var data = [{
            label: this.props.user.login,
            values: values
        }];
        console.log(data);
        return (
            <BarChart
                data={data}
                width={this.props.width}
                height={this.props.height}
                margin={{top: 10, bottom: 10, left: 10, right:10}}
            />
        );
    }
});
## module.exports = WeightlogBarChart;

I verified that data[0].values is an array of Objects with keys 'x' and 'y'.  Any help is appreciated. Thanks.

**Comment by sirivan79** [comment]
I have the same problem. For me it only happens, when there's no data available. Any help will be much appreciated. Faria have you found any solution to the problem.

**Comment by codesuki** [comment]
I'll check that out in the near future!

**Comment by mukeshsoni** [comment]
@sirivan79 instead of empty array send null or undefined when there is no data. Or you can set data to what is set in the defaultpropsmixin - 

```
if(data.length === 0) {
    data = {label: 'No data available', values: [{x: 'No data available', y: 1}]}
// OR data = undefined;
}
```

**Comment by codesuki** [comment]
Yeah that is the solution for now but that is kinda hackish. Will try to fix the cause.

**Comment by mukeshsoni** [comment]
Yeah, that's a work around. All the charts expect data with alteast one element. Need a function like `Maybe` which takes care of empty input.
