### ISSUE TITLE
BarChart label tooltip

### ISSUE THREAD

**Issue by Shachar16290** [codesuki/react-d3-components#43]
When I use the tooltipHtml attribute in a BarChart, I get only the parameters below:
  _handleTooltip(x, y0, y, total) {
  }

There is a possibility to add the label of the current bar?
I can't find any indication of which bar is it because there is not a legend either yet.

**Comment by codesuki** [comment]
I am reworking the tooltips. At the same time I will change the parameters to contain an object with label,value etc. :) 
At least that is the plan.

**Comment by Shachar16290** [comment]
Great. Thank you. Waiting for an update.
