### ISSUE TITLE
Tooltip not showing up

### ISSUE THREAD

**Issue by sharky93** [codesuki/react-d3-components#44]
The function being assigned to generate the tooltip is being called and I can access the respective 'x', 'y' etc values, but no tooltip is showing up. Tried this for the BarChart component.

**Comment by sharky93** [comment]
So, it turned out to be a silly css issue. You might wanna use not so generic classnames - ex, "tooltip" in this case.

**Comment by Reggino** [comment]
@sharky93 Thanks for info, i ran into the exact same issue.

@codesuki e.g. Bootstrap CSS styles ``` .tooltip``` making it invisible... Prefixing classes or something like that sounds like a good idea!

**Comment by codesuki** [comment]
Yep. I first thought that they will be used more specific like `#GraphA .tooltip` or something. But you guys are right I will probably put a prefix.

**Comment by f15gdsy** [comment]
Face the issue also when using with Bootstrap lol
