### ISSUE TITLE
Cannot get onMouseEnter and onMouseLeave handlers to work

### ISSUE THREAD

**Issue by sharky93** [codesuki/react-d3-components#46]
I tried with BarCharts. Is there a specific syntax?

This seems to be the place where the bug arises? - https://github.com/codesuki/react-d3-components/blob/master/src/BarChart.jsx#L120

**Comment by codesuki** [comment]
Sorry for the late response.
For now, did you consider using the `tooltipHtml` prop to implement mouse events?
