### ISSUE TITLE
DefaultScalesMixin uses different versions of props for updating

### ISSUE THREAD

**Issue by weschristiansen** [codesuki/react-d3-components#48]
The function _makeScales is called by the lifecycle function componentWillRecieveProps and is fed nextProps.  However after _makeScales, all subsequent functions called in the code path use this.props, which are the old props. 

We've fixed this by passing the nextProps down to the subsequent functions.

**Comment by codesuki** [comment]
Wow thanks for the report!! I'll have a look at that immediately :)

**Comment by codesuki** [comment]
Confirmed. Will fix and upload new version soon.

**Comment by weschristiansen** [comment]
Great! Look forward to it. Great job with the library. We're enjoying using it. 

Wes Christiansen
via - mobile
(801) 652-0589

**Comment by codesuki** [comment]
Thanks! 
You might have posted your mobile phone number which might not be on purpose.

**Comment by codesuki** [comment]
Should be fixed in 0.5.1. Also by passing it down.
