### ISSUE TITLE
Demo not loading dependencies over https

### ISSUE THREAD

**Issue by STRML** [codesuki/react-d3-components#5]
Some browsers seem to be pinning github.io to `https` - likely a recent use of [HSTS](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security). Since your scripts are not loaded over HTTPS, modern browsers will refuse to load them and the demo shows a blank white page.

You can fix this by simply changing the scripts to be protocol-agnostic (starting with `//` instead of `http://` or `https://`).

**Comment by codesuki** [comment]
Thanks! Will do :)
