### ISSUE TITLE
BarChart.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead

### ISSUE THREAD

**Issue by JoeGrasso** [codesuki/react-d3-components#60]
Needs an upgrade to React 0.14-RC1

BarChart.getDOMNode(...) is deprecated. Please use ReactDOM.findDOMNode(instance) instead

**Comment by tungv** [comment]
+1

**Comment by markgandy** [comment]
+1

**Comment by Reggino** [comment]
+1

**Comment by joshgagnon** [comment]
Made a PR for this https://github.com/codesuki/react-d3-components/pull/77

**Comment by codesuki** [comment]
Great work! Thank you.

**Comment by burgalon** [comment]
Any idea when a new NPM package will be released?

**Comment by codesuki** [comment]
True, there are some fixes that are not yet in the npm. I missed that, will release in a day.

**Comment by codesuki** [comment]
Done
