### ISSUE TITLE
'main' wrong in package.json

### ISSUE THREAD

**Issue by jos3000** [codesuki/react-d3-components#67]
It specifies `lib/index.js` which doesn't exist. It should be `dist/react-d3-components.js` I think.

**Comment by codesuki** [comment]
This is for the npm release. The files are run through babel and then put into the lib folder. After the release the lib folder is removed.
This is so you don't need babel just for this project.

**Comment by jos3000** [comment]
Thanks - I was trying to use the library via a git link in package.json. I'm using the 0.6.0 release on npm now and everything is fine.

**Comment by codesuki** [comment]
In case you want to use the github version:
```
cd react-d3-components
npm install -g .
```
or 
```
cd YourProject
npm install PATH_TO_RD3C_CLONE
```
should work :)
