### ISSUE TITLE
Changing react dependency naming from 'React' to 'react'

### ISSUE THREAD

**Issue by nicolabortignon** [codesuki/react-d3-components#68]
The official react library now is exported as 'react'. In this library we are still using the 'React' name with the capital letter.
I start getting error messages when implementing the library in other projects. 
If it's ok I'd like to PR the change.

Let me know

**Comment by codesuki** [comment]
Sure! Feel free to pullreq. I will merge :)

**Comment by nicolabortignon** [comment]
Closed by #69
