### ISSUE TITLE
Tick text should be rotatable

### ISSUE THREAD

**Issue by mbykovskyy** [codesuki/react-d3-components#70]
It would be nice to be able to rotate tick text when it's too long.

**Comment by mwhite** [comment]
FYI, I have done this and will hopefully submit a PR sooner or later.

**Comment by mbykovskyy** [comment]
I was going to implement this as well but then realised that it can be done
in CSS. The only reason I created this issue is because it doesn't work
with Phantom 1.9 because it uses an older version of Webkit which requires
a `transform` property to be set on the `text` element.

**Comment by super-cache-money** [comment]
Really keen for that PR :)

**Comment by codesuki** [comment]
Is there a PR planned? :)

**Comment by ryanhca** [comment]
Wondering when this PR is going to be submitted? I am wanting to rotate text on just one of my Charts that I'm building. I have a page with multiple charts and the only way I can think to rotate the text on the x-axis is to append some sort of class to the 'text' element and style it. However I haven't been able to figure out how to do this. Any help would be appreciated thanks!

**Comment by mwhite** [comment]
Sorry, I switched to another library and no longer have the relevant change.
