### ISSUE TITLE
xScale.rangeBand is not a function

### ISSUE THREAD

**Issue by bramdevries** [codesuki/react-d3-components#71]
I'm getting the following error on 0.6.0:

`Uncaught TypeError: xScale.rangeBand is not a function(anonymous function) @ BarChart.js:73(anonymous function)`

My component looks like this:

``` jsx
import React, {Component} from 'react'
import {BarChart} from 'react-d3-components';

export default class Graph extends Component {
  render() {
    const {history} = this.props;

    const data = [{
      label: 'Average Ping',
      values: [
        {x: 1, y: 2},
        {x: 2, y: 1},
        {x: 3, y: 3},
        {x: 4, y: 5},
      ]
    }];

    return (
      <BarChart data={data} width={500} height={500} />
    )
  }
}
```

Any clues? I'm guess that this should be coming from `DefaultScalesMixin` but for some reason isn't.

**Comment by codesuki** [comment]
Thanks for the report! I'll have a look.

**Comment by bramdevries** [comment]
Cool, this is the webpack setup I use https://github.com/madewithlove/webpack-config might be related

**Comment by mcdonnelldean** [comment]
@codesuki I'm getting the same issue. Is it anything obvious? I could take a look myself?

**Comment by codesuki** [comment]
@mcdonnelldean @bramdevries 
I think since the input data is numbers DefaultScalesMixin does not create an ordinal scale which is needed to call rangeBands if I am not mistaken.
Could you try passing your own ordinal scale and see if it fixes it?

Best case would be if this could be handled in an elegant way. I just chose to make a linear scale if the input data is numeric. So either the values need to be converted to string or there needs to be an option to force the mixin to make an ordinal scale (which seems a bit dirty but maybe cannot be helped?)

**Comment by mcdonnelldean** [comment]
Let me try an ordinal scale over the weekend and see what happens. I'll report back then.

**Comment by mdarens** [comment]
I get the same error using `Dates` as my x values in my own data, as well as when trying to reproduce the bar chart in the example folder. I'm bundling with browserify.

**Comment by codesuki** [comment]
If you pass dates it should normally make a time scale.
Could you debug and see if he jumps into this condition here?
https://github.com/codesuki/react-d3-components/blob/master/src/DefaultScalesMixin.jsx#L45

**Comment by cbougatsa** [comment]
I also get the same error when using the BarChart with any scale other than ordinal. 
Maybe because  <Bar> component always makes calculations using xScale.rangeBand().
It works as expected for the LineChart though.
Is there a workaround for this?Thnx!

**Comment by ryanhca** [comment]
this is happening for me as well. My x values are dates that look like this: `
Sat Jul 16 2016 11:43:35 GMT-0600 (MDT)`

IDK a good workaround at the moment.

**Comment by ryanhca** [comment]
UPDATE: I formatted my data text to be "Fri, 07, 15th" type of formatting. Now I'm getting this. 

`bundle.js:8490 Uncaught Invariant Violation: Objects are not valid as a React child (found: Thu Jul 21 2016 11:58:37 GMT-0600 (MDT)). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Axis`.`

**Comment by ryanhca** [comment]
UPDATE: I fixed it. One of the properties on my values array was actually still being set as a Date not a string.
