### ISSUE TITLE
modifying maximum value of yScale doesn't work

### ISSUE THREAD

**Issue by dltmd6262** [codesuki/react-d3-components#75]
Hi!

First of all thank you for such a great package! Seems like you're pretty busy.. but using plain d3 scaling of y axis doesn't work :[ 

The graph I get is this:
![2015-11-30 11 06 13](https://cloud.githubusercontent.com/assets/14027017/11462089/6f9297d6-9752-11e5-99ee-2e018399e5e7.png)

and my code for the line graph is this: 

```
        <LineChart
          data={uwd}
          width={1600}
          height={500}
          margin={{top: 10, bottom: 50, left: 50, right: 20}}
          yAxis={{outerTickSize: 0.1, label: ""}}
          yScale={d3.scale.linear().domain([0, 1]).range([0, 1])}
        />
```

My data ```uwd``` is usually between 0 and 1, but I want my y axis to always be between 0 and 1 no matter the range of the data. I tried everything related to linear scaling and they all return the same collapsed graph.. Any ideas??

**Comment by mukeshsoni** [comment]
The range function will take the pixel values for height range. So if your graph is 300 pixel high - 

```
d3.scale.linear().domain([0, 1]).range([300, 0])
```

**Comment by codesuki** [comment]
@mukeshsoni thanks for helping out!
@dltmd6262 thank you! did that fix your problem?

**Comment by dltmd6262** [comment]
wow sorry guys for such a late reply that actually worked! Thank you so much :]

**Comment by codesuki** [comment]
Great it worked out!
