### ISSUE TITLE
Tooltip labels

### ISSUE THREAD

**Issue by cookednoodles** [codesuki/react-d3-components#78]
At the moment its impossible to know what each color on a stacked barchart corresponds to.
http://codesuki.github.io/react-d3-components/example.html

the tooltip method only recieves the x, y0 and y. It would be nice for it to also get the label of the dataset something like 

this._data[this._data.length - 1].label

**Comment by codesuki** [comment]
I think I had that in an old version. I will re-add it! Thank you!

**Comment by mdarens** [comment]
I don't see this in the source for the current version. Do you still plan to re-add it?

**Comment by codesuki** [comment]
Yes, i want to return an object which consists of the datapoint and the label.
In case you have some time feel free to send a pull request I will make a release out of it!

**Comment by mdarens** [comment]
The way the callback is called between different chart types seems to be pretty customized for each one. It might make sense to consolidate this logic in the tooltip mixin or component, or in a HOC around the tooltip component.

**Comment by codesuki** [comment]
I agree. Should probably be completely rewritten. Also in a future version charts will be able to be layered onto each other, the tool tip implementation then probably needs to change.

**Comment by fedeerbes** [comment]
Hi everyone, i needed the label in the callback from tooltipHtml so, i went deeper and i changed  the Barchart.js file. For me this work fine but, if this is not a correct solution, it's ok too. =)

  _tooltipHtml: function _tooltipHtml(d) {
        var xScale = this._xScale;
        var yScale = this._yScale;

        var data = this.props.data,
            x = this.props.x,
            y= this.props.y,
            y0= this.props.y0,
            label;

        data.map( function(dataObj,i){
          for (var j in dataObj) {
            if( j == 'values'){
              dataObj[j].map( function(value, i) {
                if(value.x == x(d) && value.y == y(d) && value.y0 == y0(d)) label = dataObj['label']
              })
            }
          }
        })

        var html = this.props.tooltipHtml(this.props.x(d), this.props.y0(d), this.props.y(d), label);

        var midPoint = xScale.rangeBand() / 2;
        var xPos = midPoint + xScale(this.props.x(d));

        var topStack = this._data[this._data.length - 1].values;
        var topElement = null;

        // TODO: this might not scale if dataset is huge.
        // consider pre-computing yPos for each X
        for (var i = 0; i < topStack.length; i++) {
            if (this.props.x(topStack[i]) === this.props.x(d)) {
                topElement = topStack[i];
                break;
            }
        }
        var yPos = yScale(this.props.y0(topElement) + this.props.y(topElement));

        return [html, xPos, yPos];
    },

Sorry for my bad English, and this is great @codesuki , thanks a lot

**Comment by nhill-cpi** [comment]
Has the code been updated to allow you to access the label of the element? If my tooltip function is 
```
function(x, y0, y) {

}
```
, how can I access the element's label?

Thanks!
