### ISSUE TITLE
Whole numbers on axis

### ISSUE THREAD

**Issue by mcdonnelldean** [codesuki/react-d3-components#80]
Hi @codesuki 

First off, I've started to use this lib in anger for one of my projects so expect some kickback over christmas in terms of tidy work and that (least I can do to say thanks).

Right now I have possibly a silly issue. I am sending down whole values to a line chart but my y-axis is showing values in .5 ranges unless a given value is high enough to change the scale.

Is there a way to force scales to use whole numbers only? Have you an example of setting something like this up? I'm new enough to D3 so getting slightly lost when it comes to scales vs access and how to set this up.

**Comment by mukeshsoni** [comment]
You can pass yScale and use rangeRound - 

```
var extent = [0, whatever];
var yScale=d3.scale.linear().domain(extent).rangeRound([height, 0]);
```

**Comment by mcdonnelldean** [comment]
@mukeshsoni Awesome! Thanks for the response! That looks much easier than I thought :D Let me try it out. I presume the height is whatever height I give to my chart.

**Comment by mcdonnelldean** [comment]
Unfortunately that didn't work. Check out my screenshot.

<img width="1680" alt="screen shot 2015-12-14 at 11 36 11" src="https://cloud.githubusercontent.com/assets/3625961/11780058/0b5718ae-a257-11e5-8d71-067e817ded41.png">

My y values are always numbers, ranging from 0 to usually 15 but could go up to hundreds. The number being tracked is the message flow rate over 120 sec/s.

My code is:

```js
render: function () {
    var width = this.state.width
    var data = this.state.data

    if (data) {
      function createChart (label, data) {
        var yScale = D3.scale.linear().domain([0,1]).rangeRound([0,1,2,3,4,5,6,7,8,9,10])

        return (
          <div key={label} className="row">
            <BoxHeader icon={'fa fa-line-chart'} title={label} />
            <LineChart
              data={data}
              yScale={yScale}
              xAxis={{innerTickSize: 10, tickFormat: formatX, label: 'time' }}
              yAxis={{label: 'msgs'}}
            />
          </div>
        )
      }

      var charts = [createChart('overview', data)]
      data.forEach(function (measurement) {
        charts.push(createChart(measurement.label, measurement))
      })
    }

    return (
      <div className="report">
        {charts}
      </div>
    )
  }
```

The data is preformatted into:

```js
var data = [{label: 'foo', values: [{x: 1234, y: 2}]}]
```

With the code above I was trying to get the range to be between 0 and 10. I've tried a couple of different ways to enter this scale but I think I'm missing something. I tried adding the height to rangeRound too. It always seems to have .x in the scales until I have a sufficient spread of data to make the scale self update.

**Comment by mukeshsoni** [comment]
The extent has to be dynamic based on your y data range. you have put a constant extent of [0,1]

**Comment by mcdonnelldean** [comment]
@mukeshsoni Ah that makes sense. Ok, I'll go through the docs too

**Comment by codesuki** [comment]
Sorry I didn't reply here yet. I tried to find a good sample for it but nothing yet.
Basically what @mukeshsoni said is correct. 
Also the methods mentioned here should work too: 
https://stackoverflow.com/questions/12643591/how-to-limit-d3-svg-axis-to-integer-labels

@mukeshsoni thanks a lot for lending a helping hand!

**Comment by mukeshsoni** [comment]
My pleasure @codesuki!

We are using a fork at work and it has helped us a lot. Thanks for the great work!

**Comment by codesuki** [comment]
Great to hear it's useful! Sorry I didn't accept your last pull request but if you have anything I would be happy to merge it back in.

**Comment by mukeshsoni** [comment]
Will surely try and contribute code (or maybe documentation).
