### ISSUE TITLE
Uncaught ReferenceError: ReactD3 is not defined

### ISSUE THREAD

**Issue by richardry** [codesuki/react-d3-components#86]
I followed the following instruction:
- pull from master
- npm install & npm run build:js
- python -m SimpleHTTPServer 8000

but when navigating to http://localhost:8000/example
It doesn't work, got "Uncaught ReferenceError: ReactD3 is not defined"

**Comment by codesuki** [comment]
Let me check. 
Just for clarification, did you do this around the time you wrote the ticket or a day some time before?
Also are there any other error messages? If it cannot find React3D mostly it should throw some more errors.

**Comment by richardry** [comment]
The issue was on the code I pulled yesterday. Just did another pull, seems the previous two commits 18 hours ago fixed the problem. Sorry I should have done another pull before raising the issue. On a site note, I just come to evaluate this project and my inital impression is very good. I like your approach more than Victory's. Thanks for the good work!

**Comment by codesuki** [comment]
Thanks, I am glad it worked out! 
Not your fault, I found this issue yesterday and fixed it so just wanted to make sure you already use it :)
