### ISSUE TITLE
Installation issues due to wrong ReactDOM pointer

### ISSUE THREAD

**Issue by nicolabortignon** [codesuki/react-d3-components#88]
When I try to install this library as part of a packages, with other libraries and dependencies, 
I get this error stack:

ERROR in ./~/react-d3-components/dist/react-d3-components.js
Module not found: Error: Cannot resolve module 'ReactDOM' in /Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/dist
resolve module ReactDOM in /Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/dist
  looking for modules in /Users/nicolabortignon/tracklistme/client-react/src
    /Users/nicolabortignon/tracklistme/client-react/src/ReactDOM doesn't exist (module as directory)
    resolve 'file' ReactDOM in /Users/nicolabortignon/tracklistme/client-react/src
      resolve file
        /Users/nicolabortignon/tracklistme/client-react/src/ReactDOM doesn't exist
        /Users/nicolabortignon/tracklistme/client-react/src/ReactDOM.json doesn't exist
        /Users/nicolabortignon/tracklistme/client-react/src/ReactDOM.js doesn't exist
        /Users/nicolabortignon/tracklistme/client-react/src/ReactDOM.jsx doesn't exist
  looking for modules in /Users/nicolabortignon/tracklistme/client-react/node_modules
    /Users/nicolabortignon/tracklistme/client-react/node_modules/ReactDOM doesn't exist (module as directory)
    resolve 'file' ReactDOM in /Users/nicolabortignon/tracklistme/client-react/node_modules
      resolve file
        /Users/nicolabortignon/tracklistme/client-react/node_modules/ReactDOM doesn't exist
        /Users/nicolabortignon/tracklistme/client-react/node_modules/ReactDOM.json doesn't exist
        /Users/nicolabortignon/tracklistme/client-react/node_modules/ReactDOM.jsx doesn't exist
        /Users/nicolabortignon/tracklistme/client-react/node_modules/ReactDOM.js doesn't exist
  looking for modules in /Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules
    /Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules/ReactDOM doesn't exist (module as directory)
    resolve 'file' ReactDOM in /Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules
      resolve file
        /Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules/ReactDOM doesn't exist
        /Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules/ReactDOM.json doesn't exist
        /Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules/ReactDOM.js doesn't exist
        /Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules/ReactDOM.jsx doesn't exist
[/Users/nicolabortignon/tracklistme/client-react/src/ReactDOM]
[/Users/nicolabortignon/tracklistme/client-react/src/ReactDOM]
[/Users/nicolabortignon/tracklistme/client-react/src/ReactDOM.json]
[/Users/nicolabortignon/tracklistme/client-react/src/ReactDOM.js]
[/Users/nicolabortignon/tracklistme/client-react/src/ReactDOM.jsx]
[/Users/nicolabortignon/tracklistme/client-react/node_modules/ReactDOM]
[/Users/nicolabortignon/tracklistme/client-react/node_modules/ReactDOM]
[/Users/nicolabortignon/tracklistme/client-react/node_modules/ReactDOM.json]
[/Users/nicolabortignon/tracklistme/client-react/node_modules/ReactDOM.jsx]
[/Users/nicolabortignon/tracklistme/client-react/node_modules/ReactDOM.js]
[/Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules/ReactDOM]
[/Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules/ReactDOM]
[/Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules/ReactDOM.json]
[/Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules/ReactDOM.js]
[/Users/nicolabortignon/tracklistme/client-react/node_modules/react-d3-components/node_modules/ReactDOM.jsx]
 @ ./~/react-d3-components/dist/react-d3-components.js 3:60-79

I don't understand why it tries to look for ReactDOM instead of react-dom.
For the record, the library react-dom is available here: 
/Users/nicolabortignon/tracklistme/client-react/src/react-dom

**Comment by codesuki** [comment]
Hi there!
I will have a look at it. Thanks for the report.
Did you use the newest version?

**Comment by codesuki** [comment]
Think I found the reason but have to checks what's the correct way to do it.

**Comment by nicolabortignon** [comment]
Yeah, just for the record, i was using latest version, and also tried to point directly to the git repo (head version).

In case you wonder, here is my package.json with all the other dependencies:
https://github.com/TracklistMe/client-react/blob/master/package.json

Thanks for the help!

**Comment by nicolabortignon** [comment]
Any news on this ? 

I'm finally having some time and I'd love to start working on this library again

**Comment by codesuki** [comment]
Oh sorry! Totally forgot. Was on holiday too recently. 
Let me read this again and get back to you.

**Comment by codesuki** [comment]
I don't really get it.
I agree it should look for react-dom.
Reading up on peer-dependencies again it should be in here though:
/Users/nicolabortignon/tracklistme/client-react/node_modules/

Any reason it is in your src folder?
Maybe we can figure it out together :)

**Comment by codesuki** [comment]
Sorry it took so long >_<
