### ISSUE TITLE
Changing ticks' text position

### ISSUE THREAD

**Issue by 7091lapS** [codesuki/react-d3-components#91]
I am drawing an area chart and would like to shift the position of the text under each tick. Right now I can only do this by setting in the style `text {
      transform: translate(30px, -40px);
    }`  but as my data changes, the space between each tick also changes, and the text will end up in the wrong position. Is there a different way to change the text's position? I've tried using percentage rather than px but it does not work.

**Comment by codesuki** [comment]
I tried googling a little bit and just came up with this: https://stackoverflow.com/questions/17544546/d3-js-align-text-labels-between-ticks-on-the-axis
and
http://bl.ocks.org/mbostock/6186172

I am not sure it will help you. You could try playing with the tickFormat and override it for the axis.
( https://github.com/codesuki/react-d3-components/blob/master/src/Axis.jsx#L8 )

If you search for the problem related to D3 and find a solution it should be easily usable with this library too.
