### ISSUE TITLE
When are you gonna new release for legend?

### ISSUE THREAD

**Issue by codewoorigil** [codesuki/react-d3-components#92]
I want to use this componets on my project. But Legend is not working. I know you've already had a plan about that. I wonder when are you gonna finish to develop it.

Tell me your new release plan.

Thanks.

**Comment by codesuki** [comment]
Probably not any time soon since it's very easy to make custom legends by accessing the scales / data.

**Comment by Martindelataille** [comment]
@codesuki Can you provide an example to access the scales / data.

Thanks

**Comment by codesuki** [comment]
@Martindelataille 
Just pass your own like this example:
```
var xScale = d3.scale.ordinal(); //... + set it up appropriately
var yScale = d3.scale.linear();
var colorScale = d3.scale.category20();

<BarChart xScale={xScale}
      yScale={yScale}
      colorScale={colorScale}
      barPadding={0.3}
      data={data}
      width={400}
      height={400}
      margin={{top: 10, bottom: 50, left: 50, right: 10}}/>
```

Then you know which color will be used. (The color is just chosen linearly from the color array).
Does that help?

**Comment by mycodebucket** [comment]
could you please , give some complete example. 
i am getting ":Error: <rect> attribute height: A negative value is not valid. ("-1")"

**Comment by mycodebucket** [comment]
I am passing the values , as you have mentioned above. what you mean by "set it up appropriately". could you give some example on that?
